blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


app_name = 'blog'

urlpatterns= [
    path('', index, name='index'),
    path('sections/', SectionPageView.as_view(), name='sections'),
    path('themes/<int:pk>/', ThemePageView.as_view(), name='themes'),
    path('pablic/<int:pk>/', PablicationsView.as_view(), name='pablic'),
    path('description/<int:pk>/', DescriptionsView.as_view(), name='description'),
  #  path('search/', SearchForSiteView.as_view(), name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website_path/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('login/', include('authapp.urls')),
    path('minigame/', include('minigames.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone


class SectionModel(models.Model):
    title = models.CharField(max_length=100)
    pablish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ThemeModel(models.Model):
    section = models.ForeignKey(SectionModel, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    pablish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class PablicationModel(models.Model):
    theme = models.ForeignKey(ThemeModel, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True)
    pablish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250)

    def __str__(self):
        return self.title


class DescriptionModel(models.Model):
    pablic = models.ForeignKey(PablicationModel, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True)
    content = models.TextField(blank=True)
    image_content = models.ImageField(upload_to='media', blank=True)
    pablish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView, RedirectView
from django.http import HttpResponseRedirect
from .models import *
from django.db.models import Q


def index(request):
    return render(request, 'blog/index.html')

class SectionPageView(TemplateView):

    template_name = 'blog/sections.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sections'] = SectionModel.objects.all()
        return context

class ThemePageView(TemplateView):

    template_name = 'blog/theme.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['themes'] = ThemeModel.objects.filter(section=kwargs.get('pk'))
        return context
    
    
class PablicationsView(TemplateView):

    template_name = 'blog/pablications.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pablics'] = PablicationModel.objects.filter(theme=kwargs.get('pk'))
        return context


class DescriptionsView(TemplateView):

    template_name = 'blog/description.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['descriptions'] = DescriptionModel.objects.filter(pablic=kwargs.get('pk'))
        return context



"""class SearchForSiteView(View):
    def get(self, request):
        search_query = request.GET.get('search', '')
        search_all_contents = TableOfContents.objects.filter(Q(nameDescription__icontains=search_query) |
                                                             Q(descriptionTheme__icontains=search_query))
        
        if search_all_contents:
            v = search_all_contents.values()[0]['themeDescription_id']
            link_contents = TableOfContents.objects.filter(themeDescription=v)
            short_description = link_contents.filter().values()[0]['descriptionTheme'][:50] + '...'
            context = {'link_contents': link_contents, 'short_description': short_description}
        else:
            return HttpResponseRedirect('/')
        return render(request, 'diary/search.html', context)"""
            
        

blog/templates/blog/description.html
{% extends 'base.html' %}

{% block sidebar %}
<div class="list-group w-75" id="list-tab" role="tablist">
  {% for descr in descriptions %}
  <a class=""
     id="list-home-list"
     data-toggle="list"
     href="#{{ descr.title }}"
     role="tab"
     aria-controls="home">{{ descr.title }}</a>
</div>
{% endfor %}
{% endblock %}
{% block content %}
<div class="tab-content" id="nav-tabContent">
  <div class="col-9" style="position: relative; height: 740px; overflow-y: scroll;"> 
    {% for descr in descriptions %}
    <div class="tab-pane fade show active"
	 id="{{ descr.title }}"
	 role="tabpanel"
	 aria-labelledby="list-home-list">
      <h1 class="text-center">{{ descr.title }}</h1>
      <p>{{ descr.content }}</p>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock%}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title%}
Главная
{% endblock%}

{% block content %}
<div class="row">
  <div class="col-9 text-center mt-5">
    <h1>Важно понимать</h1>
    <p class="mt-5">На данном сайте Вы ненайдете учений. Сдесь только мысли неизвестного мне существа взявшегося из неоткуда.
      Статьи что сдесь найдете возможно будут Вам полезны, интересны, позновательны. Но никогда не воспринимайте их
      как мнение создателя сайта. Тот кто его создал просто пишет то что ему передают и соответственно прокачивает
      свои навыки кода. Этот сайт будет расти, в нем будет то что изучаю лично я по программированию, и странные истории
      от странного существа. Лично от себя могу сказать я очень полюбил программиование и постааюсь радовать залетных пользователей
      своими мини играми и основной игрой ПЛАН БЕЛИАЛА игра без плана и сюжета, которая развиваться будет на ходу на глазах тех залетных)
      Хорошего Вам времяпровождения. 
    </p>
  </div>
</div>
{% endblock%}

{% block dropdownbutton %}
{% endblock %}

blog/templates/blog/pablications.html
{% extends 'base.html' %}

{% block sidebar %}
{% for pablic in pablics %}
<a href="{% url 'blog:description' pablic.id %}">{{ pablic.title }}</a>
{% endfor %}
{% endblock %}

blog/templates/blog/sections.html
{% extends 'base.html' %}

{% block title%}
Рубрики
{% endblock%}

{% block sidebar%}
{% for section in sections %}
<a href="{% url 'blog:themes' section.id %}">{{ section }}</a>
{% endfor %}
{% endblock%}

{% block content %}
<div class="row">
  <div class="col-9 text-center mt-5">
    <h1>Добрый день, вечер, ночь. Можете называть меня Matrix.</h1>
    <p class="mt-5">Я не писатель и не психолог, да и в школе успехами не пользовался.
Поэтому уважаемый читатель этих историй, будь бдителен что читаешь. В этих историях Вы возможно найдете для себя какой то 
смысл, но сразу предупреждаю - это не мое личное мнение, эти истории скорее всего третье мнение не зависимое. Оно может 
совпадать с Вашим, а может и нет.
Для начала хотелось бы разобраться что такое (мнение). Давайте посмотрим в толковый словарь.
Мнение - Суждение, выражающее оценку чего-н., отношение к чему-н., взгляд на что-н.
Принятие суждения другого человека(что для Вас это значит?) Наверное для каждого из нас это самое сложное. Каждый начинает
вскипать внутри себя, так как затронута его точка зрения. И когда Ваши точки зрения не совпадают Вы начинаете бесить друг друга.
Но что это, за чувство в определенный момент стало не понятно. Так как ведя диалог на ту или иную тему человек стоящий пред тобой 
теряет контроль, так как твои доводы звучат убедительнее но ЭГО человека не позволяет принять Ваше мнение.
Тут то мне и захотелось писать эти истории. Люди просто не выносят меня, так как разучился чувствовать что человек стоящий передо 
мной уже себя не контролирует и несет всякую речь из своего рта но что бы доказать обратное, в то время как идет обычный на мой взгляд
диалог(да, провождение и общение с кодом, библиотеками по программированию и т.д делают свое дело). Оказывается что обычные вопросы плана
(почему так думаешь, почему ты считаешь что должно быть так, ты уверен что это что то исправит,) просто выводят стоящего человека из себя, он 
теряет контроль. Либо когда человеку предоставляешь другой взгляд на вещи он просто входит в ярость.
И так начнем:</br>
P.S. Статьи от Matrix это "Истории "Видимо я не с этой планеты""
    </p>
  </div>
</div>

{% endblock%}

blog/templates/blog/theme.html
{% extends 'base.html' %}

{% block sidebar %}
<ul class="navbar-nav">
  {% for theme in themes %}
  <li class="nav-item">
    <a class="nav-link" href=" {% url 'blog:pablic' theme.id %}"> {{theme.title }}</a>
    {% endfor %}
</ul>
{% endblock%}