blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


app_name = 'blog'

urlpatterns= [
    path('', index, name='index'),
    path('sections/', SectionPageView.as_view(), name='sections'),
    path('themes/<int:pk>/', ThemePageView.as_view(), name='themes'),
    path('pablic/<int:pk>/', PablicationsView.as_view(), name='pablic'),
    path('description/<int:pk>/', DescriptionsView.as_view(), name='description'),
  #  path('search/', SearchForSiteView.as_view(), name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minigames/urls.py
from django.urls import path
from .views import *

app_name = 'minigames'

urlpatterns = [
    path('index', index, name='index'),
    path('lotogame/', lotogame, name='lotogame'),
    path('newticket/<int:menu>/', GameMenuViews.as_view(url='/minigame/lotogame/'), name='menu'),
    path('chengeticket/<int:pk>/<int:ticket>/', ChengeTicketViews.as_view(url='/minigame/lotogame/'), name='chenge_ticket'),
    path('test/', test, name='test')

]

website_path/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('login/', include('authapp.urls')),
    path('minigame/', include('minigames.urls')),
    path('admin/', admin.site.urls),
]

minigames/models.py
from django.db import models

# Create your models here.

minigames/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic.base import RedirectView
from .settings.loto_game import Ticket, BarrelBag


ticket = Ticket()
barrel = BarrelBag()

def index(request):
    return render(request, 'minigames/index.html')


def lotogame(request):

    if len(ticket.ticket_list) > 4:
        ticket.ticket_list.clear()

    context = {'ticket': ticket, 'barrel': barrel}

    return render(request, 'minigames/loto/lotogame.html', context)


class GameMenuViews(RedirectView):

    pattern_name = 'minigames/loto/lotogame.html'

    def get_redirect_url(self, *args, **kwargs):

        if kwargs.get('menu') == 1:
            ticket.create_ticket()

        if kwargs.get('menu') == 2:
            if len(barrel.barrel_list) == 0:
                barrel.create_barrel()
            else:
                print('Delete barrel')

        if kwargs.get('menu') == 3:
            barrel.barrel_list.clear()
            ticket.ticket_list.clear()

# данное условие временно. Эту ссылку необходимо
# переделать на автоматичесскую в javascript

        if kwargs.get('menu') == 15:
            barrel.get_barrel()

        return super().get_redirect_url(*args, **kwargs)


class ChengeTicketViews(RedirectView):

    pattern_name = 'minigames/loto/lotogame.html'

    def get_redirect_url(self, *args, **kwargs):

        if kwargs.get('pk') in barrel.barrel_pop:
            ticket.cross_it_uot((kwargs.get('ticket')-1),
                                kwargs.get('pk'),)

        return super().get_redirect_url(*args, **kwargs)


def test(request):
    ticket.check_ticket(check_num=barrel.barrel_other)
    barrel.get_barrel()
    return HttpResponseRedirect('/minigame/lotogame')

minigames/templates/minigames/loto/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "minigames.css" %}">
    <title></title>

  </head>
  <body>
    <div class="container">
      <div class="row">
	<div class="col-12 col-sm-6 col-md-8">
	  {% block rest %}
	  {% endblock%}
	</div>
	<div class="col-6 col-md-4">
	  {% block menu %}
	  {% endblock%}
	</div>
      </div>	  
      {% block content  %}
      {% endblock%}
    </div>
    <script src="{% static 'minigames.js' %}"></script>

  </body>
</html>

minigames/templates/minigames/loto/lotogame.html
{% extends 'base.html' %}

{% block sidebar %}
<a href="{% url 'minigames:menu' 1  %}">Взять билет</a>
<a href="{% url 'minigames:menu' 2  %}">Начать игру</a>
<a href="{% url 'minigames:menu' 3  %}">Закончить игру</a>
{% endblock%}

{% block content %}
<div class="row">
  <div class="col">
    {% if barrel.barrel_list|length > 30 %}
    <!--данную реализацию заменить на jquery-->
    <div class="gamego"></div>
    <p class="getbarrel">
      {{ barrel.barrel_pop }}
      <button>{{ barrel.get_barrel }}</button>
    </p>
    {% endif %}
  </div>
</div>
<div class="tickets">
<div class="row">
  <div class="col">
    {% if ticket.ticket_list|length >= 1 %}
      {% for i in ticket.ticket_list|slice:":2" %}
      {% autoescape off %}{% cycle 1 2 as num %}{% endautoescape %}

      <table class="table table-sm w-50 table-td">
	{% for j in i %}
	<tr class="table-tr">
	  {% for x in j %}
	  <td class="table-td">
	    <a href="{% url 'minigames:chenge_ticket' x num %}">{{ x }}</a>
	  </td>
	  {% endfor %}
	</tr>
	{% endfor %}
      </table>
      {% endfor %}
    {% endif %}
  </div>
  <div class="col">
    {% if ticket.ticket_list|length >= 3 %}
      {% for i in ticket.ticket_list|slice:"2:" %}
      {% autoescape off %}{% cycle 3 4 as num %}{% endautoescape %}

      <table class="table table-sm w-50 table-hover table-td">
	{% for j in i %}
	<tr class="table-tr">
	  {% for x in j %}
	  <td class="table-td">
	    <a href="{% url 'minigames:chenge_ticket' x num %}">{{ x }}</a>
	  </td>
	  {% endfor %}
	</tr>
	{% endfor %}
      </table>
      {% endfor %}
    {% endif %}
  </div>
</div>
</div>
{% endblock%}