authapp/urls.py
from django.urls import path
from django.conf.urls import include
from .views import *

app_name = 'authapp'

urlpatterns = [
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
    path('registred/', registred, name='registred'),
]

blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


app_name = 'blog'

urlpatterns= [
    path('', index, name='index'),
    path('sections/', SectionPageView.as_view(), name='sections'),
    path('themes/<int:pk>/', ThemePageView.as_view(), name='themes'),
    path('pablic/<int:pk>/', PablicationsView.as_view(), name='pablic'),
    path('description/<int:pk>/', DescriptionsView.as_view(), name='description'),
  #  path('search/', SearchForSiteView.as_view(), name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minigames/urls.py
from django.urls import path
from .views import *

app_name = 'minigames'

urlpatterns = [
    path('index', index, name='index'),
    path('lotogame/', lotogame, name='lotogame'),
    path('newticket/<int:menu>/', GameMenuViews.as_view(url='/minigame/lotogame/'), name='menu'),
    path('chengeticket/<int:pk>/<int:ticket>/', ChengeTicketViews.as_view(url='/minigame/lotogame/'), name='chenge_ticket'),
    path('test/', test, name='test')

]

website_path/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('login/', include('authapp.urls')),
    path('minigame/', include('minigames.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="full" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/stylefiles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/minigames.css" %}">
    <title>
      {% block title%}
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      <div class="container">
	<div class="row text-center">
	  <div class="col"><a href="{% url 'blog:sections' %}">My_Diary</a></div>
	  <div class="col"><a href="{% url 'minigames:index' %}">Minigames</a></div>
	  <div class="col"><a href="">Plan_Bellial</a></div>
	  <div class="col"><a href="">Help</a></div>
	</div>
      </div>
    </header>
    <main>
      <div class="container-fluid">
	<div class="row">
	  <div class="col-3">
	    <nav class="nav flex-column">
	      {% block sidebar %}
	      {% endblock %}
	    </nav>	    
	  </div>
	  <div class="col">
	    {% block content %}
	    {% endblock%}
	  </div>
      </div>
    </main>
    <footer class="fixed-bottom">
      <div class="container">
	<div class="row">
	  <div class="col-12">
	    <form action="">
	      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		Where_to_send
		{% block dropdownbutton %}
		{% endblock %}
	      </button>
	      <div class="dropdown-menu">
		<a class="dropdown-item" href="{% url 'blog:index' %}">Home</a>
		<a class="dropdown-item" href="{% url 'authapp:login' %}">Login</a>
		<a class="dropdown-item" href="{% url 'authapp:registred' %}">Registred</a>
	      </div>
	      <input class="w-75 rounded" name="send-masseges" type="text" />
	      <input class="btn" type="submit" value="Send" />
	    </form>
	  </div>
	</div>
      </div>
    </footer>
    <script type="text/javascript" src="{% static 'js/minigames.js' %}"></script>
  </body>
</html>